name: BankSystem
version: '${version}'
main: com.github.majisyou.banksystem.BankSystem
api-version: 1.18
softdepend: [Vault]
authors: [ majisyou ]

commands:
  emerald:
    description: bank
    usage: you dont open bank
    permission: Bank.user
    aliases: bank

  bank:
    description: bank
    usage: you dont open bank
    permission: Bank.user


  send:
    description: send
    usage: /send <player> <emerald>
    permission: Bank.user
    aliases: pay

  summon_banker:
    description: summon
    usage: 失敗
    permission: Bank.op